name: "Build iOS app"

# on: [push]
on: [workflow_dispatch]

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: build archive and ipaify
        run: |
          wget -O archive.zip "https://www.dropbox.com/scl/fi/5dmzevbfqc4a9eakt7suf/370cec66-0794-11f1-94a2-9828a60d55de.zip?rlkey=w0c7rv9opyk1k0fqu37864q6o&dl=1"
          unzip archive.zip -d .

          xcodebuild archive -project sugar-run.xcodeproj -scheme 'sugar-run' -archivePath sugar-run.xcarchive -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

          mkdir Payload
          mv sugar-run.xcarchive/Products/Applications/sugar-run.app Payload/sugar-run.app

          zip -r "sugar-run.ipa" "Payload"

          mv sugar-run.ipa ${{ runner.temp }}/sugar-run.ipa


      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: sugar-run
          path: ${{ runner.temp }}/sugar-run.ipa
          # you can also archive the entire directory
          # path: ${{ runner.temp }}/build
          retention-days: 3